namespace: "fortinet"
name: "fortiswitch"
version: "1.2.0"
description: "A collection of Ansible Modules for FortiSwitch v7"
readme: "README.md"
authors:
    - Frank Shen (@frankshen01)
    - Hongbin Lu (@fgtdev-hblu)
    - Link Zheng (@chillancezen)
    - Jie Xue (@JieX19)
    - Miguel Angel Munoz (@mamunozgonzalez)
dependencies: {
    "ansible.netcommon": "*"
}
license:
    - "GPL-3.0-or-later"
tags:
    - fortiswitch
    - networking
    - firewall
    - security
    - fortinet
repository: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection/tree/fsw_v7.0.0/galaxy_1.2.0"
documentation: "https://ansible-galaxy-fortiswitch-docs.readthedocs.io/en/galaxy-1.2.0"
homepage: "https://www.fortinet.com"
issues: "https://github.com/fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection/issues"
