objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi:
    fortiswitch:
      description: HttpApi Plugin for Fortinet FortiSwitch Appliance or VM
      name: fortiswitch
      version_added: 1.0.0
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.1.3
